### ISSUE TITLE
Error when compiling caused by latest Los commit

### ISSUE THREAD

**Issue by acras01** [AospExtended/platform_frameworks_av#11]
Got error while building after repo sync last evening

https://del.dog/golujocena.rb

that commit in los source caused that
https://github.com/LineageOS/android_vendor_qcom_opensource_audio/commit/acf624493aae07a82ff17723e85a8fdbfc4c3166

Have our devs checked this commit in LOS sources, wich should be considered when merging previous?
https://github.com/LineageOS/android_frameworks_av/commit/97fa3267a

**Comment by theimpulson** [comment]
This will be fixed after merging latest Android Security Patch. It will be merged soon after we finish merging open commits on gerrit. You can manually revert that audio commit or wait for us to merge stuff.
